title: UNICORN | accelerator
email: contato@unicornbr.com.br
description: >
  A Unicorn é uma aceleradora que irá auxiliar Startups de todo Brasil, 
  em todas as etapas. Ela é a ferramenta onde se conectarão ideias de pequenas 
  empresas com mentalidade inovadoras, dotadas de poucos recursos 
  e a vontade de empreender em nossa cidade.
baseurl: ""
url: "http://unicornbr.com.br"

markdown: kramdown
