title: UNICORN | accelerator
email: contato@unicornbr.com.br
description: >
  A Unicorn é uma aceleradora que irá auxiliar Startups de todo Brasil, 
  em todas as etapas. Somos um grupo de pesquisadores, investidores 
  e jovens talentos que acredita no cenário do empreendedorismo de Brasília 
  e tem como objetivo fomentar essa área junto a iniciativas de todo o país.
baseurl: ""
url: "http://unicornbr.com.br"

markdown: kramdown
